language: java
dist: trusty
sudo: false # faster builds

jdk:
    - oraclejdk8
#    - openjdk8

script:
#    - cd dubbo-cluster
#    - mvn clean install
    - ls
    - pwd
    - cd dubbo-common
    - mvn clean install
    - cd ../dubbo-config
    - mvn clean install
    - cd ../dubbo-container
    - mvn clean install
    - cd ../dubbo-demo
    - mvn clean install
    - cd ../dubbo-filter
    - mvn clean install
    - cd ../dubbo-monitor
    - mvn clean install
    - cd ../dubbo-plugin
    - mvn clean install
    - cd ../dubbo-registry
    - mvn clean install
    - cd ../dubbo-remoting
    - mvn clean install
    - cd ../dubbo-rpc
    - mvn clean install
    - cd ..
#    - mvn clean package
#    - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
