language: java
dist: trusty
os:linux

jdk:
    - oraclejdk8
#    - openjdk8

script:
#    - cd dubbo-cluster
#    - mvn clean install
    - ls
    - pwd

#    - mvn clean package
#    - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
